#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TEST_ROOT=$(mktemp -d)
trap 'rm -rf "$TEST_ROOT"' EXIT

fail() {
    echo "not ok - $1" >&2
    exit 1
}

assert_contains() {
    local file=$1
    local expected=$2
    grep -F -- "$expected" "$file" >/dev/null || fail "Expected $file to contain: $expected"
}

assert_call_count() {
    local expected=$1
    local actual
    actual=$(find "$AGENT_CALLS" -type f -name 'args.*' | wc -l | tr -d ' ')
    [ "$actual" = "$expected" ] || fail "Expected $expected agent call(s), got $actual"
}

setup_home() {
    export HOME="$TEST_ROOT/home-$1"
    mkdir -p "$HOME/.config/gitai/prompts"
    cp "$PROJECT_ROOT"/prompts/*.txt "$HOME/.config/gitai/prompts/"
}

setup_stubs() {
    local name=$1
    STUB_DIR="$TEST_ROOT/stubs-$name"
    PI_CALLS="$TEST_ROOT/pi-calls-$name"
    AGENT_CALLS=$PI_CALLS
    export PI_CALLS AGENT_CALLS
    mkdir -p "$STUB_DIR" "$PI_CALLS"

    cat >"$STUB_DIR/pi" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
call=$(find "$PI_CALLS" -type f -name 'args.*' | wc -l | tr -d ' ')
call=$((call + 1))
printf '%s\n' "$@" >"$PI_CALLS/args.$call"
cat >"$PI_CALLS/stdin.$call"
if [ "${PI_EMPTY_RESPONSE:-}" = 1 ]; then
    exit 0
fi
if grep -F 'Your task is to write a concise and informative title' "$PI_CALLS/args.$call" >/dev/null; then
    printf '%s\n' '{"title":"Improve pi integration","body":"## Summary\n\n- Use pi once"}'
else
    printf '%s\n' 'feat: use pi agent'
fi
EOF
    chmod +x "$STUB_DIR/pi"
    export PATH="$STUB_DIR:$PATH"
}

stub_agent() {
    local command=$1
    local response=${2:-feat: use selected agent}
    cat >"$STUB_DIR/$command" <<EOF
#!/usr/bin/env bash
set -euo pipefail
call=\$(find "\$AGENT_CALLS" -type f -name 'args.*' | wc -l | tr -d ' ')
call=\$((call + 1))
printf '%s\n' "\$@" >"\$AGENT_CALLS/args.\$call"
cat >"\$AGENT_CALLS/stdin.\$call"
if [ "\$(basename "\$0")" = omp ]; then
    echo "Working..." >&2
fi
for arg in "\$@"; do
    case "\$arg" in
        @*)
            attachment=\${arg#@}
            [ -f "\$attachment" ] && cat "\$attachment" >"\$AGENT_CALLS/attachment.\$call"
            ;;
    esac
done
if [ "\${AGENT_FAIL_STDOUT:-}" = 1 ]; then
    echo "agent failure written to stdout"
    exit 1
fi
printf '%s\n' '$response'
EOF
    chmod +x "$STUB_DIR/$command"
}

init_repo() {
    local repo=$1
    git init -q -b main "$repo"
    git -C "$repo" config user.name Test
    git -C "$repo" config user.email test@example.com
    echo initial >"$repo/file.txt"
    git -C "$repo" add file.txt
    git -C "$repo" commit -q -m initial
}

test_commit_message_uses_pi() {
    setup_home commit
    setup_stubs commit
    local repo="$TEST_ROOT/commit-repo"
    init_repo "$repo"
    echo changed >"$repo/file.txt"
    git -C "$repo" add file.txt
    echo existing >"$repo/message"

    (
        cd "$repo"
        EDITOR=true GITAI_AGENT=pi GITAI_MODEL=google/test-model "$PROJECT_ROOT/ai-commit-msg" message
    )

    assert_call_count 1
    assert_contains "$PI_CALLS/args.1" "--print"
    assert_contains "$PI_CALLS/args.1" "--no-session"
    assert_contains "$PI_CALLS/args.1" "--no-tools"
    assert_contains "$PI_CALLS/args.1" "google/test-model"
    assert_contains "$PI_CALLS/stdin.1" "+changed"
    [ "$(head -n1 "$repo/message")" = "feat: use pi agent" ] || fail "Commit message was not generated by pi"
    echo "ok - ai-commit-msg uses pi"
}

test_tag_uses_pi() {
    setup_home tag
    setup_stubs tag
    local repo="$TEST_ROOT/tag-repo"
    init_repo "$repo"

    printf 'n\n' | (
        cd "$repo"
        EDITOR=true GITAI_AGENT=pi GITAI_MODEL=google/test-model "$PROJECT_ROOT/aitag" v1.0.0
    )

    assert_call_count 1
    assert_contains "$PI_CALLS/args.1" "--print"
    assert_contains "$PI_CALLS/args.1" "--no-tools"
    assert_contains "$PI_CALLS/stdin.1" "diff --git a/file.txt b/file.txt"
    assert_contains "$PI_CALLS/stdin.1" "+initial"
    echo "ok - aitag uses pi"
}

test_tag_rejects_empty_pi_response() {
    setup_home empty-tag
    setup_stubs empty-tag
    local repo="$TEST_ROOT/empty-tag-repo"
    local output="$TEST_ROOT/empty-tag-output"
    init_repo "$repo"

    if printf 'n\n' | (
        cd "$repo"
        EDITOR=true GITAI_AGENT=pi PI_EMPTY_RESPONSE=1 "$PROJECT_ROOT/aitag" v1.0.0
    ) >"$output" 2>&1; then
        fail "Expected aitag to reject an empty pi response"
    fi

    assert_contains "$output" "AI agent returned an empty tag message"
    [ -z "$(git -C "$repo" tag --list)" ] || fail "An empty tag message must not create a tag"
    echo "ok - aitag rejects an empty pi response"
}

test_pr_uses_pi_once_for_title_and_body() {
    setup_home pr
    setup_stubs pr
    local repo="$TEST_ROOT/pr-repo"
    local remote="$TEST_ROOT/pr-remote.git"
    git init -q --bare "$remote"
    init_repo "$repo"
    git -C "$repo" remote add origin "$remote"
    git -C "$repo" push -q -u origin main
    git -C "$repo" switch -q -c feature
    echo feature >"$repo/file.txt"
    git -C "$repo" commit -qam feature
    git -C "$repo" push -q -u origin feature

    cat >"$STUB_DIR/gh" <<'EOF'
#!/usr/bin/env bash
case "$1 $2" in
    "repo view")
        printf '%s\n' '{"defaultBranchRef":{"name":"main"},"name":"repo","owner":{"login":"owner"}}'
        ;;
    "pr list")
        printf '%s' "${GH_ONGOING:-}"
        ;;
    "pr view")
        printf '%s\n' '{"body":"## Existing body"}'
        ;;
    *)
        printf 'Unexpected gh invocation: %s\n' "$*" >&2
        exit 1
        ;;
esac
EOF
    chmod +x "$STUB_DIR/gh"

    printf 'n\n' | (
        cd "$repo"
        EDITOR=true GITAI_AGENT=pi GITAI_MODEL=google/test-model "$PROJECT_ROOT/aipr"
    ) >"$TEST_ROOT/aipr-output"

    assert_call_count 1
    assert_contains "$PI_CALLS/args.1" "--print"
    assert_contains "$PI_CALLS/args.1" "--no-tools"
    assert_contains "$PI_CALLS/args.1" "Your task is to write a concise and informative title"
    assert_contains "$PI_CALLS/args.1" "Write a clear, informative pull request message"
    assert_contains "$PI_CALLS/stdin.1" "+feature"
    assert_contains "$TEST_ROOT/aipr-output" "Improve pi integration"
    assert_contains "$TEST_ROOT/aipr-output" "Use pi once"
    echo "ok - aipr generates title and body with one pi call"

    printf 'n\n' | (
        cd "$repo"
        EDITOR=true GH_ONGOING=42 GITAI_AGENT=pi GITAI_MODEL=google/test-model "$PROJECT_ROOT/aipr" --update-title
    ) >"$TEST_ROOT/aipr-update-output"

    assert_call_count 2
    assert_contains "$PI_CALLS/args.2" "Your task is to write a concise and informative title"
    assert_contains "$PI_CALLS/args.2" "## Existing body"
    assert_contains "$TEST_ROOT/aipr-update-output" "Improve pi integration"
    assert_contains "$TEST_ROOT/aipr-update-output" "Use pi once"
    echo "ok - aipr updates title and body with one pi call"
}

test_configured_agents_use_their_cli_contract() {
    local configured command expected
    for configured in oh-my-pi codex claude-code; do
        setup_home "agent-$configured"
        setup_stubs "agent-$configured"
        case "$configured" in
            oh-my-pi)
                command=omp
                expected=--no-tools
                ;;
            codex)
                command=codex
                expected=--ephemeral
                ;;
            claude-code)
                command=claude
                expected=--no-session-persistence
                ;;
        esac
        rm "$STUB_DIR/pi"
        stub_agent "$command"
        local repo="$TEST_ROOT/agent-$configured-repo"
        init_repo "$repo"
        echo changed >"$repo/file.txt"
        git -C "$repo" add file.txt
        : >"$repo/message"

        (
            cd "$repo"
            EDITOR=true GITAI_AGENT="$configured" GITAI_MODEL=test-model \
                "$PROJECT_ROOT/ai-commit-msg" message
        )

        assert_call_count 1
        assert_contains "$AGENT_CALLS/args.1" "$expected"
        assert_contains "$AGENT_CALLS/args.1" "test-model"
        if [ "$configured" = oh-my-pi ]; then
            [ -f "$AGENT_CALLS/attachment.1" ] || fail "Expected oh-my-pi input to be passed as an @file attachment"
            assert_contains "$AGENT_CALLS/attachment.1" "+changed"
            if grep -F "Working..." "$repo/message" >/dev/null; then
                fail "Expected oh-my-pi progress output to stay out of the commit message"
            fi
        else
            assert_contains "$AGENT_CALLS/stdin.1" "+changed"
        fi
        if [ "$configured" = claude-code ]; then
            assert_contains "$AGENT_CALLS/args.1" "Use the supplied input to complete the task."
            local prompt_line tools_line
            prompt_line=$(grep -nFx "Use the supplied input to complete the task." "$AGENT_CALLS/args.1" | cut -d: -f1)
            tools_line=$(grep -nFx -- "--tools" "$AGENT_CALLS/args.1" | cut -d: -f1)
            [ "$prompt_line" -lt "$tools_line" ] || \
                fail "Expected the Claude prompt before the variadic --tools option"
        fi
    done
    echo "ok - configured agents use their CLI contracts"
}

test_agent_stdout_failure_is_reported() {
    setup_home agent-stdout-failure
    setup_stubs agent-stdout-failure
    rm "$STUB_DIR/pi"
    stub_agent claude
    local repo="$TEST_ROOT/agent-stdout-failure-repo"
    local output="$TEST_ROOT/agent-stdout-failure-output"
    init_repo "$repo"
    echo changed >"$repo/file.txt"
    git -C "$repo" add file.txt
    : >"$repo/message"

    if (
        cd "$repo"
        EDITOR=true AGENT_FAIL_STDOUT=1 GITAI_AGENT=claude-code \
            "$PROJECT_ROOT/ai-commit-msg" message
    ) >"$output" 2>&1; then
        fail "Expected an agent failure written to stdout to fail"
    fi
    assert_contains "$output" "agent failure written to stdout"
    echo "ok - agent failures written to stdout are reported"
}

test_agent_auto_detection_order() {
    setup_home agent-detection
    setup_stubs agent-detection
    stub_agent omp
    stub_agent codex
    stub_agent claude
    local repo="$TEST_ROOT/agent-detection-repo"
    init_repo "$repo"
    echo changed >"$repo/file.txt"
    git -C "$repo" add file.txt
    : >"$repo/message"

    (
        cd "$repo"
        PATH="$STUB_DIR:/usr/bin:/bin" EDITOR=true "$PROJECT_ROOT/ai-commit-msg" message
    )
    assert_contains "$AGENT_CALLS/args.1" "--no-context-files"

    rm "$STUB_DIR/pi"
    : >"$repo/message"
    (
        cd "$repo"
        PATH="$STUB_DIR:/usr/bin:/bin" EDITOR=true "$PROJECT_ROOT/ai-commit-msg" message
    )
    assert_contains "$AGENT_CALLS/args.2" "--no-rules"

    rm "$STUB_DIR/omp"
    : >"$repo/message"
    (
        cd "$repo"
        PATH="$STUB_DIR:/usr/bin:/bin" EDITOR=true "$PROJECT_ROOT/ai-commit-msg" message
    )
    assert_contains "$AGENT_CALLS/args.3" "--ephemeral"

    rm "$STUB_DIR/codex"
    : >"$repo/message"
    (
        cd "$repo"
        PATH="$STUB_DIR:/usr/bin:/bin" EDITOR=true "$PROJECT_ROOT/ai-commit-msg" message
    )
    assert_contains "$AGENT_CALLS/args.4" "--no-session-persistence"
    echo "ok - agent auto-detection follows pi, oh-my-pi, codex, claude-code order"
}

test_commit_hook_resolves_runner_through_symlink() {
    setup_home symlink-hook
    setup_stubs symlink-hook
    local repo="$TEST_ROOT/symlink-hook-repo"
    init_repo "$repo"
    mkdir "$repo/hooks"
    ln -s "$PROJECT_ROOT/ai-commit-msg" "$repo/hooks/prepare-commit-msg"
    echo changed >"$repo/file.txt"
    git -C "$repo" add file.txt
    : >"$repo/message"

    (
        cd "$repo"
        GITAI_AGENT=pi "$repo/hooks/prepare-commit-msg" message
    )
    assert_call_count 1
    echo "ok - commit hook resolves the agent runner through a symlink"
}

test_no_available_agent_is_an_error() {
    setup_home no-agent
    local repo="$TEST_ROOT/no-agent-repo"
    local output="$TEST_ROOT/no-agent-output"
    init_repo "$repo"
    echo changed >"$repo/file.txt"
    git -C "$repo" add file.txt
    : >"$repo/message"

    if (
        cd "$repo"
        PATH=/usr/bin:/bin EDITOR=true "$PROJECT_ROOT/ai-commit-msg" message
    ) >"$output" 2>&1; then
        fail "Expected ai-commit-msg to fail when no supported agent is installed"
    fi
    assert_contains "$output" "No supported AI agent found"
    echo "ok - missing agents produce a clear error"
}

test_configured_unavailable_agent_is_an_error() {
    local output="$TEST_ROOT/unavailable-agent-output"
    if PATH=/usr/bin:/bin GITAI_AGENT=codex "$PROJECT_ROOT/gitai-agent" --check >"$output" 2>&1; then
        fail "Expected an unavailable configured agent to fail"
    fi
    assert_contains "$output" "Configured AI agent 'codex' requires the 'codex' command"
    echo "ok - unavailable configured agent produces a clear error"
}

test_model_help_is_consistent() {
    setup_home help
    local aipr_help="$TEST_ROOT/aipr-help"
    local aitag_help="$TEST_ROOT/aitag-help"

    (
        cd "$PROJECT_ROOT"
        ./aipr --help
    ) >"$aipr_help"
    (
        cd "$PROJECT_ROOT"
        ./aitag --help
    ) >"$aitag_help"

    assert_contains "$aipr_help" "--model <model>"
    assert_contains "$aipr_help" "Model to use with the selected AI agent"
    assert_contains "$aitag_help" "--model <model>"
    assert_contains "$aitag_help" "Model to use with the selected AI agent"
    echo "ok - --model help is consistent"
}

test_brew_development_links_can_be_restored() {
    local brew_prefix="$TEST_ROOT/homebrew"
    local brew_stub_dir="$TEST_ROOT/brew-stub"
    local brew_log="$TEST_ROOT/brew.log"
    mkdir -p "$brew_prefix/bin" "$brew_stub_dir"

    cat >"$brew_stub_dir/brew" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case "$1" in
    --prefix)
        printf '%s\n' "$TEST_BREW_PREFIX"
        ;;
    unlink | link)
        printf '%s\n' "$*" >>"$TEST_BREW_LOG"
        ;;
    *)
        printf 'Unexpected brew invocation: %s\n' "$*" >&2
        exit 1
        ;;
esac
EOF
    chmod +x "$brew_stub_dir/brew"

    PATH="$brew_stub_dir:$PATH" TEST_BREW_PREFIX="$brew_prefix" TEST_BREW_LOG="$brew_log" \
        "$PROJECT_ROOT/scripts/brew-dev-link" link

    assert_contains "$brew_log" "unlink gitai"
    for command in aipr aitag ai-commit-msg gitai-agent gitai-common.sh; do
        [ -L "$brew_prefix/bin/$command" ] || fail "Expected a development link for $command"
        [ "$(readlink "$brew_prefix/bin/$command")" = "$PROJECT_ROOT/$command" ] || \
            fail "Development link for $command has the wrong target"
    done

    PATH="$brew_stub_dir:$PATH" TEST_BREW_PREFIX="$brew_prefix" TEST_BREW_LOG="$brew_log" \
        "$PROJECT_ROOT/scripts/brew-dev-link" restore

    assert_contains "$brew_log" "link gitai"
    for command in aipr aitag ai-commit-msg gitai-agent gitai-common.sh; do
        [ ! -e "$brew_prefix/bin/$command" ] || fail "Expected development link for $command to be removed"
    done
    echo "ok - brew development links can be restored"
}

test_github_integration_script_cli() {
    local help_output="$TEST_ROOT/github-integration-help"
    local error_output="$TEST_ROOT/github-integration-error"

    "$PROJECT_ROOT/tests/integration-github.sh" --help >"$help_output"
    assert_contains "$help_output" "--keep-repo"
    assert_contains "$help_output" "pi, oh-my-pi, codex, and claude-code"
    assert_contains "$help_output" "ai-commit-msg, aitag, and aipr"

    if "$PROJECT_ROOT/tests/integration-github.sh" --unknown >"$error_output" 2>&1; then
        fail "Expected the GitHub integration script to reject unknown flags"
    fi
    assert_contains "$error_output" "Unknown option: --unknown"
    echo "ok - GitHub integration script exposes a safe CLI"
}

test_github_integration_requires_cleanup_permission() {
    local stub_dir="$TEST_ROOT/github-integration-stubs"
    local output="$TEST_ROOT/github-integration-auth-error"
    local gh_log="$TEST_ROOT/github-integration-gh.log"
    mkdir -p "$stub_dir"

    for command in pi omp codex; do
        cat >"$stub_dir/$command" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
        chmod +x "$stub_dir/$command"
    done

    cat >"$stub_dir/claude" <<'EOF'
#!/usr/bin/env bash
if [ "$1 $2" = "auth status" ]; then
    printf '%s\n' '{"loggedIn":true,"authMethod":"test"}'
fi
exit 0
EOF
    chmod +x "$stub_dir/claude"

    cat >"$stub_dir/gh" <<'EOF'
#!/usr/bin/env bash
if [ "$1 $2" = "auth status" ]; then
    printf '%s\n' '{"hosts":{"github.com":[{"state":"success","active":true,"scopes":"repo, read:org"}]}}'
    exit 0
fi
printf '%s\n' "$*" >>"$TEST_GH_LOG"
exit 99
EOF
    chmod +x "$stub_dir/gh"

    if PATH="$stub_dir:$PATH" TEST_GH_LOG="$gh_log" \
        "$PROJECT_ROOT/tests/integration-github.sh" >"$output" 2>&1; then
        fail "Expected GitHub integration to require repository cleanup permission"
    fi
    assert_contains "$output" "delete_repo"
    [ ! -e "$gh_log" ] || fail "GitHub integration created resources before checking cleanup permission"
    echo "ok - GitHub integration checks cleanup permission before creating resources"
}

test_github_integration_checks_claude_auth_before_creating_repo() {
    local stub_dir="$TEST_ROOT/github-claude-auth-stubs"
    local output="$TEST_ROOT/github-claude-auth-error"
    local gh_log="$TEST_ROOT/github-claude-auth-gh.log"
    mkdir -p "$stub_dir"

    for command in pi omp codex; do
        cat >"$stub_dir/$command" <<'EOF'
#!/usr/bin/env bash
exit 0
EOF
        chmod +x "$stub_dir/$command"
    done

    cat >"$stub_dir/claude" <<'EOF'
#!/usr/bin/env bash
if [ "$1 $2" = "auth status" ]; then
    printf '%s\n' '{"loggedIn":false,"authMethod":"none"}'
    exit 1
fi
exit 0
EOF
    chmod +x "$stub_dir/claude"

    cat >"$stub_dir/gh" <<'EOF'
#!/usr/bin/env bash
if [ "$1 $2" = "auth status" ]; then
    printf '%s\n' '{"hosts":{"github.com":[{"state":"success","active":true,"scopes":"repo"}]}}'
    exit 0
fi
printf '%s\n' "$*" >>"$TEST_GH_LOG"
exit 99
EOF
    chmod +x "$stub_dir/gh"

    if PATH="$stub_dir:$PATH" TEST_GH_LOG="$gh_log" \
        "$PROJECT_ROOT/tests/integration-github.sh" --keep-repo >"$output" 2>&1; then
        fail "Expected GitHub integration to reject unauthenticated Claude Code"
    fi
    assert_contains "$output" "claude auth login"
    [ ! -e "$gh_log" ] || fail "GitHub integration created resources before checking Claude authentication"
    echo "ok - GitHub integration checks Claude authentication before creating resources"
}

test_entrypoints_load_shared_functions() {
    local common="$PROJECT_ROOT/gitai-common.sh"
    [ -f "$common" ] || fail "Expected shared functions in gitai-common.sh"

    for entrypoint in ai-commit-msg aipr aitag; do
        # The assertion intentionally searches for a literal shell variable reference.
        # shellcheck disable=SC2016
        assert_contains "$PROJECT_ROOT/$entrypoint" '. "$GITAI_COMMON_SCRIPT"'
        if grep -E '^(spin_animation|kill_spin|cleanup|check_required_commands|is_git_repo)\(\)' \
            "$PROJECT_ROOT/$entrypoint" >/dev/null; then
            fail "Expected $entrypoint to use shared common functions"
        fi
    done
    echo "ok - entrypoints load shared functions"
}

test_shared_json_response_extraction() {
    # Loaded dynamically from the checkout under test.
    # shellcheck disable=SC1091
    . "$PROJECT_ROOT/gitai-common.sh"
    local expected='{"title":"Expected title","body":"Expected body"}'
    local actual

    actual=$(printf 'Claude status output\n%s\nDone\n' "$expected" | gitai_extract_json_object)
    [ "$(printf '%s\n' "$actual" | jq -c .)" = "$expected" ] || \
        fail "Expected JSON extraction to ignore surrounding text"

    # Backticks are literal Markdown fence characters.
    # shellcheck disable=SC2016
    actual=$(printf '```json\n%s\n```\n' "$expected" | gitai_extract_json_object)
    [ "$(printf '%s\n' "$actual" | jq -c .)" = "$expected" ] || \
        fail "Expected JSON extraction to remove a Markdown fence"
    echo "ok - shared JSON extraction tolerates agent formatting"
}

test_shared_code_fence_stripping() {
    # Loaded dynamically from the checkout under test.
    # shellcheck disable=SC1091
    . "$PROJECT_ROOT/gitai-common.sh"
    local actual

    # A fence wrapping the whole response is removed, blank lines preserved.
    actual=$(printf '```\nline one\n\nline two\n```\n' | gitai_strip_code_fence)
    [ "$actual" = $'line one\n\nline two' ] || fail "Expected a full fence to be stripped"

    # An inline fence inside prose is left untouched.
    actual=$(printf 'line one\n```\nline two\n```\n' | gitai_strip_code_fence)
    [ "$actual" = $'line one\n```\nline two\n```' ] || fail "Expected an inline fence to pass through"

    # An opening fence with no closing fence is left untouched.
    actual=$(printf '```\nunclosed\n' | gitai_strip_code_fence)
    [ "$actual" = $'```\nunclosed' ] || fail "Expected an unclosed fence to pass through"

    # An explicit language on the opening fence is stripped too.
    actual=$(printf '```markdown\nheading\n```\n' | gitai_strip_code_fence)
    [ "$actual" = "heading" ] || fail "Expected a fenced block with a language to be stripped"

    # Leading blank lines and leading whitespace are trimmed.
    actual=$(printf '\n\n  chore: commit subject\nbody\n' | gitai_strip_code_fence)
    [ "$actual" = $'chore: commit subject\nbody' ] || \
        fail "Expected leading blank lines and whitespace to be trimmed"

    # Leading trim also applies inside a fence.
    actual=$(printf '```\n\n  chore: commit subject\n```\n' | gitai_strip_code_fence)
    [ "$actual" = "chore: commit subject" ] || \
        fail "Expected leading trim inside a fenced block"
    echo "ok - shared code fence stripping tolerates agent formatting"
}

test_commit_message_strips_code_fence() {
    setup_home commit-fence
    setup_stubs commit-fence
    # Backticks are literal Markdown fence characters.
    # shellcheck disable=SC2016
    local fenced='```

  chore(devtools): update Brewfile

- Add grafana tap
```'
    stub_agent pi "$fenced"
    local repo="$TEST_ROOT/commit-fence-repo"
    init_repo "$repo"
    echo changed >"$repo/file.txt"
    git -C "$repo" add file.txt
    : >"$repo/message"

    (
        cd "$repo"
        EDITOR=true GITAI_AGENT=pi "$PROJECT_ROOT/ai-commit-msg" message
    )

    if grep -Fq '```' "$repo/message"; then
        fail "Expected Markdown code fences to be stripped from the commit message"
    fi
    [ "$(head -n1 "$repo/message")" = "chore(devtools): update Brewfile" ] || \
        fail "Expected leading blank lines and whitespace to be trimmed from the commit message"
    echo "ok - ai-commit-msg strips a Markdown code fence and leading whitespace"
}

test_tag_strips_code_fence() {
    setup_home tag-fence
    setup_stubs tag-fence
    # Backticks are literal Markdown fence characters.
    # shellcheck disable=SC2016
    local fenced='```
Release v1.0.0

- Add grafana tap
```'
    stub_agent pi "$fenced"
    local repo="$TEST_ROOT/tag-fence-repo"
    init_repo "$repo"

    printf 'y\n' | (
        cd "$repo"
        EDITOR=true GITAI_AGENT=pi "$PROJECT_ROOT/aitag" v1.0.0
    )

    if git -C "$repo" tag -n99 v1.0.0 | grep -Fq '```'; then
        fail "Expected Markdown code fences to be stripped from the tag message"
    fi
    git -C "$repo" tag -n99 v1.0.0 | grep -Fq "Release v1.0.0" || \
        fail "Tag message body was not preserved"
    echo "ok - aitag strips a Markdown code fence"
}

test_commit_message_uses_pi
test_tag_uses_pi
test_tag_rejects_empty_pi_response
test_pr_uses_pi_once_for_title_and_body
test_configured_agents_use_their_cli_contract
test_agent_stdout_failure_is_reported
test_agent_auto_detection_order
test_commit_hook_resolves_runner_through_symlink
test_no_available_agent_is_an_error
test_configured_unavailable_agent_is_an_error
test_model_help_is_consistent
test_brew_development_links_can_be_restored
test_github_integration_script_cli
test_github_integration_requires_cleanup_permission
test_github_integration_checks_claude_auth_before_creating_repo
test_entrypoints_load_shared_functions
test_shared_json_response_extraction
test_shared_code_fence_stripping
test_commit_message_strips_code_fence
test_tag_strips_code_fence
