#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TEST_ROOT=$(mktemp -d)
trap 'rm -rf "$TEST_ROOT"' EXIT

fail() {
    echo "not ok - $1" >&2
    exit 1
}

assert_contains() {
    local file=$1
    local expected=$2
    grep -F -- "$expected" "$file" >/dev/null || fail "Expected $file to contain: $expected"
}

assert_call_count() {
    local expected=$1
    local actual
    actual=$(find "$PI_CALLS" -type f -name 'args.*' | wc -l | tr -d ' ')
    [ "$actual" = "$expected" ] || fail "Expected $expected pi call(s), got $actual"
}

setup_home() {
    export HOME="$TEST_ROOT/home-$1"
    mkdir -p "$HOME/.config/gitai/prompts"
    cp "$PROJECT_ROOT"/prompts/*.txt "$HOME/.config/gitai/prompts/"
}

setup_stubs() {
    local name=$1
    STUB_DIR="$TEST_ROOT/stubs-$name"
    PI_CALLS="$TEST_ROOT/pi-calls-$name"
    export PI_CALLS
    mkdir -p "$STUB_DIR" "$PI_CALLS"

    cat >"$STUB_DIR/pi" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
call=$(find "$PI_CALLS" -type f -name 'args.*' | wc -l | tr -d ' ')
call=$((call + 1))
printf '%s\n' "$@" >"$PI_CALLS/args.$call"
cat >"$PI_CALLS/stdin.$call"
if [ "${PI_EMPTY_RESPONSE:-}" = 1 ]; then
    exit 0
fi
if grep -F 'Your task is to write a concise and informative title' "$PI_CALLS/args.$call" >/dev/null; then
    printf '%s\n' '{"title":"Improve pi integration","body":"## Summary\n\n- Use pi once"}'
else
    printf '%s\n' 'feat: use pi agent'
fi
EOF
    chmod +x "$STUB_DIR/pi"
    export PATH="$STUB_DIR:$PATH"
}

init_repo() {
    local repo=$1
    git init -q -b main "$repo"
    git -C "$repo" config user.name Test
    git -C "$repo" config user.email test@example.com
    echo initial >"$repo/file.txt"
    git -C "$repo" add file.txt
    git -C "$repo" commit -q -m initial
}

test_commit_message_uses_pi() {
    setup_home commit
    setup_stubs commit
    local repo="$TEST_ROOT/commit-repo"
    init_repo "$repo"
    echo changed >"$repo/file.txt"
    git -C "$repo" add file.txt
    echo existing >"$repo/message"

    (
        cd "$repo"
        EDITOR=true GITAI_MODEL=google/test-model "$PROJECT_ROOT/ai-commit-msg" message
    )

    assert_call_count 1
    assert_contains "$PI_CALLS/args.1" "--print"
    assert_contains "$PI_CALLS/args.1" "--no-session"
    assert_contains "$PI_CALLS/args.1" "--no-tools"
    assert_contains "$PI_CALLS/args.1" "google/test-model"
    assert_contains "$PI_CALLS/stdin.1" "+changed"
    [ "$(head -n1 "$repo/message")" = "feat: use pi agent" ] || fail "Commit message was not generated by pi"
    echo "ok - ai-commit-msg uses pi"
}

test_tag_uses_pi() {
    setup_home tag
    setup_stubs tag
    local repo="$TEST_ROOT/tag-repo"
    init_repo "$repo"

    printf 'n\n' | (
        cd "$repo"
        EDITOR=true GITAI_MODEL=google/test-model "$PROJECT_ROOT/aitag" v1.0.0
    )

    assert_call_count 1
    assert_contains "$PI_CALLS/args.1" "--print"
    assert_contains "$PI_CALLS/args.1" "--no-tools"
    assert_contains "$PI_CALLS/stdin.1" "diff --git a/file.txt b/file.txt"
    assert_contains "$PI_CALLS/stdin.1" "+initial"
    echo "ok - aitag uses pi"
}

test_tag_rejects_empty_pi_response() {
    setup_home empty-tag
    setup_stubs empty-tag
    local repo="$TEST_ROOT/empty-tag-repo"
    local output="$TEST_ROOT/empty-tag-output"
    init_repo "$repo"

    if printf 'n\n' | (
        cd "$repo"
        EDITOR=true PI_EMPTY_RESPONSE=1 "$PROJECT_ROOT/aitag" v1.0.0
    ) >"$output" 2>&1; then
        fail "Expected aitag to reject an empty pi response"
    fi

    assert_contains "$output" "pi returned an empty tag message"
    [ -z "$(git -C "$repo" tag --list)" ] || fail "An empty tag message must not create a tag"
    echo "ok - aitag rejects an empty pi response"
}

test_pr_uses_pi_once_for_title_and_body() {
    setup_home pr
    setup_stubs pr
    local repo="$TEST_ROOT/pr-repo"
    local remote="$TEST_ROOT/pr-remote.git"
    git init -q --bare "$remote"
    init_repo "$repo"
    git -C "$repo" remote add origin "$remote"
    git -C "$repo" push -q -u origin main
    git -C "$repo" switch -q -c feature
    echo feature >"$repo/file.txt"
    git -C "$repo" commit -qam feature
    git -C "$repo" push -q -u origin feature

    cat >"$STUB_DIR/gh" <<'EOF'
#!/usr/bin/env bash
case "$1 $2" in
    "repo view")
        printf '%s\n' '{"defaultBranchRef":{"name":"main"},"name":"repo","owner":{"login":"owner"}}'
        ;;
    "pr list")
        printf '%s' "${GH_ONGOING:-}"
        ;;
    "pr view")
        printf '%s\n' '{"body":"## Existing body"}'
        ;;
    *)
        printf 'Unexpected gh invocation: %s\n' "$*" >&2
        exit 1
        ;;
esac
EOF
    chmod +x "$STUB_DIR/gh"

    printf 'n\n' | (
        cd "$repo"
        EDITOR=true GITAI_MODEL=google/test-model "$PROJECT_ROOT/aipr"
    ) >"$TEST_ROOT/aipr-output"

    assert_call_count 1
    assert_contains "$PI_CALLS/args.1" "--print"
    assert_contains "$PI_CALLS/args.1" "--no-tools"
    assert_contains "$PI_CALLS/args.1" "Your task is to write a concise and informative title"
    assert_contains "$PI_CALLS/args.1" "Write a clear, informative pull request message"
    assert_contains "$PI_CALLS/stdin.1" "+feature"
    assert_contains "$TEST_ROOT/aipr-output" "Improve pi integration"
    assert_contains "$TEST_ROOT/aipr-output" "Use pi once"
    echo "ok - aipr generates title and body with one pi call"

    printf 'n\n' | (
        cd "$repo"
        EDITOR=true GH_ONGOING=42 GITAI_MODEL=google/test-model "$PROJECT_ROOT/aipr" --update-title
    ) >"$TEST_ROOT/aipr-update-output"

    assert_call_count 2
    assert_contains "$PI_CALLS/args.2" "Your task is to write a concise and informative title"
    assert_contains "$PI_CALLS/args.2" "## Existing body"
    assert_contains "$TEST_ROOT/aipr-update-output" "Improve pi integration"
    assert_contains "$TEST_ROOT/aipr-update-output" "Use pi once"
    echo "ok - aipr updates title and body with one pi call"
}

test_model_help_is_consistent() {
    setup_home help
    local aipr_help="$TEST_ROOT/aipr-help"
    local aitag_help="$TEST_ROOT/aitag-help"

    (
        cd "$PROJECT_ROOT"
        ./aipr --help
    ) >"$aipr_help"
    (
        cd "$PROJECT_ROOT"
        ./aitag --help
    ) >"$aitag_help"

    assert_contains "$aipr_help" "--model <model>"
    assert_contains "$aipr_help" "pi model or model pattern to use"
    assert_contains "$aitag_help" "--model <model>"
    assert_contains "$aitag_help" "pi model or model pattern to use"
    echo "ok - --model help is consistent"
}

test_brew_development_links_can_be_restored() {
    local brew_prefix="$TEST_ROOT/homebrew"
    local brew_stub_dir="$TEST_ROOT/brew-stub"
    local brew_log="$TEST_ROOT/brew.log"
    mkdir -p "$brew_prefix/bin" "$brew_stub_dir"

    cat >"$brew_stub_dir/brew" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case "$1" in
    --prefix)
        printf '%s\n' "$TEST_BREW_PREFIX"
        ;;
    unlink | link)
        printf '%s\n' "$*" >>"$TEST_BREW_LOG"
        ;;
    *)
        printf 'Unexpected brew invocation: %s\n' "$*" >&2
        exit 1
        ;;
esac
EOF
    chmod +x "$brew_stub_dir/brew"

    PATH="$brew_stub_dir:$PATH" TEST_BREW_PREFIX="$brew_prefix" TEST_BREW_LOG="$brew_log" \
        "$PROJECT_ROOT/scripts/brew-dev-link" link

    assert_contains "$brew_log" "unlink gitai"
    for command in aipr aitag ai-commit-msg; do
        [ -L "$brew_prefix/bin/$command" ] || fail "Expected a development link for $command"
        [ "$(readlink "$brew_prefix/bin/$command")" = "$PROJECT_ROOT/$command" ] || \
            fail "Development link for $command has the wrong target"
    done

    PATH="$brew_stub_dir:$PATH" TEST_BREW_PREFIX="$brew_prefix" TEST_BREW_LOG="$brew_log" \
        "$PROJECT_ROOT/scripts/brew-dev-link" restore

    assert_contains "$brew_log" "link gitai"
    for command in aipr aitag ai-commit-msg; do
        [ ! -e "$brew_prefix/bin/$command" ] || fail "Expected development link for $command to be removed"
    done
    echo "ok - brew development links can be restored"
}

test_commit_message_uses_pi
test_tag_uses_pi
test_tag_rejects_empty_pi_response
test_pr_uses_pi_once_for_title_and_body
test_model_help_is_consistent
test_brew_development_links_can_be_restored
